/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooMyPdf.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(RooMyPdf) 

 RooMyPdf::RooMyPdf(const char *name, const char *title, 
                        RooAbsReal& _full) :
   RooAbsPdf(name,title), 
   full("full","full",this,_full)
 { 
 } 


 RooMyPdf::RooMyPdf(const RooMyPdf& other, const char* name) :  
   RooAbsPdf(other,name), 
   full("full",this,other.full)
 { 
 } 



 Double_t RooMyPdf::evaluate() const 
 { 
   if(full > 0){
     //   cout << " greater 0 " << endl;
     return full;
   }
   else {
     //  cout << "not greateer " << endl;
     return 0;
     }

 } 



